/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cineshow.telas.cadastroFilme;

/**
 *
 * @author walac
 */

import com.mycompany.cineshow.Filme;
import com.mycompany.cineshow.telas.dashBoard.TelaDashBoard;
import java.awt.Toolkit;
import java.util.*;
import javax.swing.JOptionPane;

public class CadastroFilme extends javax.swing.JFrame {

    ControlaCadastroFilme cf = new ControlaCadastroFilme();
    private ArrayList<Filme> filmes;
    
    public CadastroFilme() {
        initComponents();
        filmes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdTitulo = new javax.swing.JTextField();
        tfdClassificacao = new javax.swing.JTextField();
        tfdGenero = new javax.swing.JTextField();
        tfdDuracao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVoltar = new java.awt.Button();
        btnAdicionarCartaz = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfdSinopse = new javax.swing.JTextArea();
        btnVerFilmes = new java.awt.Button();
        btnCadastrar = new java.awt.Button();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome do Filme:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 140, 20);

        jLabel2.setText("Classificação Indicativa:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 130, 160, 20);

        jLabel3.setText("Cartaz:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 440, 100, 20);

        jLabel4.setText("Sinopse:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 310, 100, 20);

        tfdTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTituloActionPerformed(evt);
            }
        });
        getContentPane().add(tfdTitulo);
        tfdTitulo.setBounds(10, 90, 790, 30);
        getContentPane().add(tfdClassificacao);
        tfdClassificacao.setBounds(10, 150, 790, 30);
        getContentPane().add(tfdGenero);
        tfdGenero.setBounds(10, 210, 790, 30);

        tfdDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDuracaoActionPerformed(evt);
            }
        });
        getContentPane().add(tfdDuracao);
        tfdDuracao.setBounds(10, 270, 790, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulário de Cadastramento de Filme");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 820, 40);

        jLabel6.setText("Gênero:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 50, 20);

        jLabel7.setText("Duração:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 250, 60, 20);

        btnVoltar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnVoltar.setLabel("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(280, 500, 80, 30);

        btnAdicionarCartaz.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarCartaz.setLabel("Adicionar Arquivo");
        btnAdicionarCartaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCartazActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarCartaz);
        btnAdicionarCartaz.setBounds(10, 460, 130, 30);

        tfdSinopse.setColumns(20);
        tfdSinopse.setLineWrap(true);
        tfdSinopse.setRows(5);
        jScrollPane2.setViewportView(tfdSinopse);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 330, 790, 90);

        btnVerFilmes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnVerFilmes.setLabel("Ver Filmes");
        btnVerFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFilmesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerFilmes);
        btnVerFilmes.setBounds(480, 500, 80, 30);

        btnCadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCadastrar.setLabel("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(380, 500, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTituloActionPerformed

    private void tfdDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDuracaoActionPerformed

    private void btnAdicionarCartazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCartazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarCartazActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaDashBoard telaDashBoard = new TelaDashBoard();
        telaDashBoard.setExtendedState(TelaDashBoard.MAXIMIZED_BOTH);
        this.dispose();
        telaDashBoard.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVerFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFilmesActionPerformed
        dlgMostraFilmes dlg = new dlgMostraFilmes(null,true,cf);
        dlg.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.dispose();
        dlg.setVisible(true);
    }//GEN-LAST:event_btnVerFilmesActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String titulo = tfdTitulo.getText();
        String sinopse = tfdSinopse.getText();
        String classificacaoText = tfdClassificacao.getText();
        String genero = tfdGenero.getText();
        String duracao = tfdDuracao.getText();
        int classificacao;
        if (titulo.isEmpty() || sinopse.isEmpty() || classificacaoText.isEmpty() || genero.isEmpty() || duracao.isEmpty()) 
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        else{
            classificacao = Integer.parseInt(classificacaoText);
            Filme filme = new Filme(titulo,sinopse,classificacao,genero, duracao);
            
            if(cf.salvar(filme)){
                this.filmes.add(filme);
                JOptionPane.showMessageDialog(null,"Filme cadastrado com sucesso");
                tfdTitulo.setText("");
                tfdSinopse.setText("");
                tfdClassificacao.setText("");
                tfdGenero.setText("");
                tfdDuracao.setText("");
                tfdTitulo.requestFocus();             
            }
            else
                JOptionPane.showMessageDialog(null,"Erro ao cadastrar o filme");
        }    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdicionarCartaz;
    private java.awt.Button btnCadastrar;
    private java.awt.Button btnVerFilmes;
    private java.awt.Button btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfdClassificacao;
    private javax.swing.JTextField tfdDuracao;
    private javax.swing.JTextField tfdGenero;
    private javax.swing.JTextArea tfdSinopse;
    private javax.swing.JTextField tfdTitulo;
    // End of variables declaration//GEN-END:variables
}
