/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cineshow.telas.telaIngresso;

import com.mycompany.cineshow.telas.dashBoard.TelaDashBoard;
import com.mycompany.cineshow.telas.dashBoard.TelaDashBoardFuncionario;

/**
 *
 * @author emman
 */
public class TelaDeIngresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaDePagamento
     */
    public TelaDeIngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pagamento = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jPanelBoleto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfdPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdtiposPagamento = new javax.swing.JComboBox<>();
        tfdPrecoFinal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelCartao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdSessões = new javax.swing.JComboBox<>();
        tfAssentosNum = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        tfdClientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Pagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pagamento.setText("Ingressos");
        getContentPane().add(Pagamento);
        Pagamento.setBounds(390, 30, 80, 25);
        Pagamento.getAccessibleContext().setAccessibleName("Pagamento");

        getContentPane().add(canvas1);
        canvas1.setBounds(678, 209, 0, 0);

        jPanelBoleto.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço do Ticket"));

        jLabel2.setText("Tipo de Ingresso");

        tfdPreco.setBackground(new java.awt.Color(255, 255, 255));
        tfdPreco.setDisabledTextColor(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Preço");

        tfdtiposPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inteira", "Meia-entrada" }));
        tfdtiposPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdtiposPagamentoActionPerformed(evt);
            }
        });

        tfdPrecoFinal.setEditable(false);
        tfdPrecoFinal.setBackground(new java.awt.Color(255, 255, 255));
        tfdPrecoFinal.setDisabledTextColor(new java.awt.Color(255, 0, 0));

        jLabel7.setText("Preço final");

        javax.swing.GroupLayout jPanelBoletoLayout = new javax.swing.GroupLayout(jPanelBoleto);
        jPanelBoleto.setLayout(jPanelBoletoLayout);
        jPanelBoletoLayout.setHorizontalGroup(
            jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBoletoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBoletoLayout.createSequentialGroup()
                        .addComponent(tfdtiposPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(tfdPrecoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBoletoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanelBoletoLayout.setVerticalGroup(
            jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdtiposPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdPrecoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBoleto);
        jPanelBoleto.setBounds(30, 340, 840, 120);
        jPanelBoleto.getAccessibleContext().setAccessibleName("Preço");

        jPanelCartao.setBorder(javax.swing.BorderFactory.createTitledBorder("Sessão"));
        jPanelCartao.setLayout(null);

        jLabel1.setText("Sessão");
        jPanelCartao.add(jLabel1);
        jLabel1.setBounds(28, 26, 60, 16);

        jLabel6.setText("Numero do Assento");
        jPanelCartao.add(jLabel6);
        jLabel6.setBounds(30, 90, 150, 16);

        tfdSessões.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdSessõesActionPerformed(evt);
            }
        });
        jPanelCartao.add(tfdSessões);
        tfdSessões.setBounds(30, 50, 770, 22);

        tfAssentosNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        tfAssentosNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAssentosNumActionPerformed(evt);
            }
        });
        jPanelCartao.add(tfAssentosNum);
        tfAssentosNum.setBounds(30, 110, 250, 22);

        getContentPane().add(jPanelCartao);
        jPanelCartao.setBounds(30, 150, 840, 170);

        jLabel5.setText("Selecione o cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 90, 210, 16);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(630, 500, 110, 23);

        btnConfirmar.setText("Pagar");
        btnConfirmar.setActionCommand("Pagar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(755, 500, 110, 23);
        btnConfirmar.getAccessibleContext().setAccessibleName("Pagar");

        tfdClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdClientesActionPerformed(evt);
            }
        });
        getContentPane().add(tfdClientes);
        tfdClientes.setBounds(40, 110, 250, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdtiposPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdtiposPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtiposPagamentoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void tfdClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdClientesActionPerformed

    private void tfdSessõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdSessõesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdSessõesActionPerformed

    private void tfAssentosNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAssentosNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAssentosNumActionPerformed

    public static void desenha (String user){
        //usuario = user;
        TelaDeIngresso TelaDeIngresso = new TelaDeIngresso();
        int width = 900;
        int height = 580;
        TelaDeIngresso.setSize(width, height);
       TelaDeIngresso.setLocationRelativeTo(null);
        TelaDeIngresso.setResizable(false);
        TelaDeIngresso.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDeIngresso.desenha(null);;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pagamento;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBoleto;
    private javax.swing.JPanel jPanelCartao;
    private javax.swing.JComboBox<String> tfAssentosNum;
    private javax.swing.JComboBox<String> tfdClientes;
    private javax.swing.JTextField tfdPreco;
    private javax.swing.JTextField tfdPrecoFinal;
    private javax.swing.JComboBox<String> tfdSessões;
    private javax.swing.JComboBox<String> tfdtiposPagamento;
    // End of variables declaration//GEN-END:variables
}
