/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cineshow.telas.telaIngresso;

import com.mycompany.cineshow.CartaoPagamento;
import com.mycompany.cineshow.Data;
import com.mycompany.cineshow.PagamentoBoleto;
import com.mycompany.cineshow.PagamentoCartao;
import com.mycompany.cineshow.exceptions.CartaoException;
import com.mycompany.cineshow.exceptions.DataException;
import com.mycompany.cineshow.telas.dashBoard.TelaDashBoard;

import java.awt.*;
import java.util.Random;

import javax.swing.JOptionPane;

/**
 *
 * @author emman
 */
public class TelaDePagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaDePagamento
     */
    public TelaDePagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Pagamento = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jPanelBoleto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfdCodigoBarras1 = new javax.swing.JTextField();
        tiposPagamento = new javax.swing.JComboBox<>();
        jPanelCartao = new javax.swing.JPanel();
        tfdNome = new javax.swing.JTextField();
        tfdNumeroCartao = new javax.swing.JTextField();
        tfdValidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdCVV1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelPix = new javax.swing.JPanel();
        tfdCodigoBarras = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        tfdValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Pagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pagamento.setText("Pagamento");
        getContentPane().add(Pagamento);
        Pagamento.setBounds(390, 30, 97, 25);
        Pagamento.getAccessibleContext().setAccessibleName("Pagamento");

        getContentPane().add(canvas1);
        canvas1.setBounds(678, 209, 0, 0);

        jPanelBoleto.setBorder(javax.swing.BorderFactory.createTitledBorder("Boleto"));

        jLabel2.setText("Código de Barras");

        tfdCodigoBarras1.setEditable(false);
        tfdCodigoBarras1.setBackground(new java.awt.Color(255, 255, 255));
        tfdCodigoBarras1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanelBoletoLayout = new javax.swing.GroupLayout(jPanelBoleto);
        jPanelBoleto.setLayout(jPanelBoletoLayout);
        jPanelBoletoLayout.setHorizontalGroup(
            jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel2)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBoletoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tfdCodigoBarras1)
                    .addContainerGap()))
        );
        jPanelBoletoLayout.setVerticalGroup(
            jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoletoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanelBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoletoLayout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(tfdCodigoBarras1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );

        getContentPane().add(jPanelBoleto);
        jPanelBoleto.setBounds(30, 310, 400, 170);
        jPanelBoleto.getAccessibleContext().setAccessibleName("Boleto");

        tiposPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "Boleto", "Pix" }));
        tiposPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(tiposPagamento);
        tiposPagamento.setBounds(30, 90, 250, 22);

        jPanelCartao.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartão"));
        jPanelCartao.setLayout(null);

        tfdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeActionPerformed(evt);
            }
        });
        jPanelCartao.add(tfdNome);
        tfdNome.setBounds(28, 48, 769, 22);
        jPanelCartao.add(tfdNumeroCartao);
        tfdNumeroCartao.setBounds(30, 110, 285, 22);
        jPanelCartao.add(tfdValidade);
        tfdValidade.setBounds(390, 110, 163, 22);

        jLabel1.setText("Nome do titular");
        jPanelCartao.add(jLabel1);
        jLabel1.setBounds(28, 26, 84, 16);

        jLabel4.setText("Validade (DD/MM/AAAA)");
        jPanelCartao.add(jLabel4);
        jLabel4.setBounds(390, 90, 136, 20);

        jLabel6.setText("Número do cartão");
        jPanelCartao.add(jLabel6);
        jLabel6.setBounds(30, 90, 97, 16);
        jPanelCartao.add(tfdCVV1);
        tfdCVV1.setBounds(660, 110, 137, 22);

        jLabel8.setText("CVC");
        jPanelCartao.add(jLabel8);
        jLabel8.setBounds(660, 90, 136, 20);

        getContentPane().add(jPanelCartao);
        jPanelCartao.setBounds(30, 130, 840, 170);

        jPanelPix.setBorder(javax.swing.BorderFactory.createTitledBorder("PIX"));

        tfdCodigoBarras.setEditable(false);
        tfdCodigoBarras.setBackground(new java.awt.Color(255, 255, 255));
        tfdCodigoBarras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setText("Copia e Cola");

        javax.swing.GroupLayout jPanelPixLayout = new javax.swing.GroupLayout(jPanelPix);
        jPanelPix.setLayout(jPanelPixLayout);
        jPanelPixLayout.setHorizontalGroup(
            jPanelPixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfdCodigoBarras)
                .addContainerGap())
            .addGroup(jPanelPixLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel7)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanelPixLayout.setVerticalGroup(
            jPanelPixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPixLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanelPix);
        jPanelPix.setBounds(460, 310, 410, 170);
        jPanelPix.getAccessibleContext().setAccessibleName("PIX");

        jLabel5.setText("Selecione o tipo de pagamento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 70, 210, 16);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(630, 500, 110, 23);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnConfirmarActionPerformed(evt);
                } catch (CartaoException e) {
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
                } catch (DataException e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(755, 500, 110, 23);

        tfdValor.setEditable(true);
        tfdValor.setBackground(new java.awt.Color(255, 255, 255));
        tfdValor.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfdValor);
        tfdValor.setBounds(730, 90, 137, 22);

        jLabel3.setText("Valor da Compra");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 70, 136, 20);

        pack();
    }// </editor-fold>                        

    private void tiposPagamentoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String item = (String) tiposPagamento.getSelectedItem();
        if(item.equals("Boleto")){

            tfdNome.setEditable(false);
            tfdNumeroCartao.setEditable(false);
            tfdCVV1.setEditable(false);
            tfdValidade.setEditable(false);
            String codigoBarras = "26090.20819 96123.397737 55900.000005 3 94220000010000 ";
            tfdCodigoBarras.setText("");
            tfdCodigoBarras1.setText(codigoBarras);
            
        } else if (item.equals("Pix")){

            Random rand = new Random();
            int num = rand.nextInt(100000, 45000000);
            
            tfdNome.setEditable(false);
            tfdNumeroCartao.setEditable(false);
            tfdCVV1.setEditable(false);
            tfdValidade.setEditable(false);
            String chavePix = "00020126330014br.gov.bcb-" + "CINESHOW" + tfdValor.getText() +  num;
            tfdCodigoBarras1.setText("");
            tfdCodigoBarras.setText(chavePix);
        }
    }                                              

    private void tfdNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
        TelaIngresso.desenha(usuario);
    }                                         

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) throws CartaoException, DataException{                                             
        String item = (String) tiposPagamento.getSelectedItem();

        if(item.equals("Cartão")){
            
            String nomeTitular = tfdNome.getText();
            String numeroCartao = tfdNumeroCartao.getText();
            int cvc = Integer.parseInt(tfdCVV1.getText());
            String validade = tfdValidade.getText();
            double valor = Double.parseDouble(tfdValor.getText());

            CartaoPagamento cartao = new CartaoPagamento(numeroCartao, nomeTitular, validade, cvc);

            if(!CartaoPagamento.validarNumeroCartao(numeroCartao)){
                throw new CartaoException("Cartão com número inválido!");
            }

            if(tfdCVV1.getText().length() != 3 && cvc > 999){
                throw new CartaoException("Cartão com CVC inválido!");
            }

            try {
                Data.parser(validade);
            } catch (DataException e) {
                throw new DataException();
            }

            if(CartaoPagamento.validarCartao(cartao) == true){
                
                PagamentoCartao pagarComCartao = new PagamentoCartao(valor, cartao);

                pagarComCartao.efetuarPagamento();
                JOptionPane.showMessageDialog(null,"Pagamento Confirmado no valor de " + tfdValor.getText() + " reais para " + tfdNome.getText() + ".","Sucesso",JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null,"Não foi possível efetuar a compra. Revise seus dados e tente novamente","Falha na solicitação",JOptionPane.ERROR_MESSAGE);
            }

            this.dispose();
            TelaIngresso.desenha(usuario);

        } else if(item.equals("Boleto")){

            JOptionPane.showMessageDialog(null,"Boleto gerado!","Sucesso",JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null,"Pix Copia e Cola gerado!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    public static void desenha (String user){
        usuario = user;
        TelaDePagamento telaIngresso = new TelaDePagamento();
        int width = 900;
        int height = 570;
        telaIngresso.setSize(width, height);
        telaIngresso.setLocationRelativeTo(null);
        telaIngresso.setResizable(false);
        telaIngresso.setVisible(true);

    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDePagamento.desenha(usuario);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Pagamento;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelBoleto;
    private javax.swing.JPanel jPanelCartao;
    private javax.swing.JPanel jPanelPix;
    private javax.swing.JTextField tfdCVV1;
    private javax.swing.JTextField tfdCodigoBarras;
    private javax.swing.JTextField tfdCodigoBarras1;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdNumeroCartao;
    private javax.swing.JTextField tfdValidade;
    private javax.swing.JTextField tfdValor;
    private javax.swing.JComboBox<String> tiposPagamento;
    private static String usuario;
    // End of variables declaration                   
}
