/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cineshow.telas.telaIngresso;

import com.mycompany.cineshow.telas.dashBoard.TelaDashBoard;
import com.mycompany.cineshow.telas.dashBoard.TelaDashBoardFuncionario;

import java.awt.*;

/**
 *
 * @author walac
 */
public class TelaIngresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaIngresso
     */
    public TelaIngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butVoltar = new javax.swing.JButton();
        butConfirmar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel2.setLayout(null);

        jLabel4.setText("CPF");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 40, 30, 16);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(50, 40, 100, 22);

        jButton1.setText("Verificar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jButton1);
        jButton1.setBounds(160, 40, 80, 23);

        jLabel1.setText("Nome");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 80, 33, 16);

        jPanel2.add(jTextField2);
        jTextField2.setBounds(50, 80, 300, 22);

        jLabel5.setText("Endereço");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 120, 60, 16);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(70, 120, 280, 22);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(450, 120, 300, 22);

        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(410, 80, 37, 16);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(450, 80, 300, 22);

        jLabel8.setText("Telefone");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(400, 120, 50, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 24, 885, 220);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresso"));
        jPanel3.setLayout(null);

        jLabel6.setText("Filme");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 30, 40, 16);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(50, 30, 250, 22);

        jLabel9.setText("Tipo");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 80, 40, 16);

        jPanel3.add(jTextField7);
        jTextField7.setBounds(50, 80, 71, 22);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(230, 80, 71, 22);

        jLabel11.setText("Sala");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(340, 30, 30, 16);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(370, 30, 90, 22);

        jLabel12.setText("Assento");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(530, 30, 43, 16);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(580, 30, 77, 22);

        jLabel13.setText("Preço");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(180, 80, 40, 16);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 250, 885, 170);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Venda de Ingresso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 0, 120, 30);

        butVoltar.setText("Voltar");
        butVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(butVoltar);
        butVoltar.setBounds(340, 440, 90, 23);

        butConfirmar.setText("Confirmar");
        butConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(butConfirmar);
        butConfirmar.setBounds(470, 440, 90, 23);

        pack();
    }// </editor-fold>                        

    private void butVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        if(usuario.equals("admin"))
            TelaDashBoard.desenha(usuario);
        else
            TelaDashBoardFuncionario.desenha(usuario);
    }

    private void butConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
        /*this.dispose();
        TelaDePagamento.desenha(usuario);*/
    }

    public static void desenha (String user){
        usuario = user;
        TelaIngresso telaIngresso = new TelaIngresso();
        int width = 900;
        int height = 550;
        telaIngresso.setSize(width, height);
        telaIngresso.setLocationRelativeTo(null);
        telaIngresso.setResizable(false);
        telaIngresso.setVisible(true);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton butVoltar;
    private javax.swing.JButton butConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private static String usuario;
}
