/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cineshow.telas.dashBoard;

import com.mycompany.cineshow.telas.cadastramentoFuncionario.dlgMostraFuncionarios;
import com.mycompany.cineshow.telas.cadastroFilme.dlgMostraFilmes;
import com.mycompany.cineshow.telas.telaCadCliente.TelaCadCliente;
import com.mycompany.cineshow.telas.telaIngresso.TelaIngresso;
import com.mycompany.cineshow.telas.telaSessoes.TelaSessoes;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import javax.swing.*;
/**
 *
 * @author walac
 */
public class TelaDashBoard extends JFrame {

    /**
     * Creates new form TelaDashBoard
     */
    public TelaDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel6 = new JLabel();
        butCadCliente = new Button();
        butCadFilme = new Button();
        butCadFuncionario = new Button();
        butSessoes = new Button();
        butIngressos = new Button();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(0, 0, 0));

        jLabel1.setFont(new Font("Rage Italic", 0, 24)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("CineShow");

        jLabel6.setBackground(new Color(0, 0, 0));
        jLabel6.setFont(new Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel6.setForeground(new Color(0, 0, 255));
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText("Bem vindo ao CineShow!");
        jLabel6.setBorder(BorderFactory.createCompoundBorder());

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 850, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 230);

        butCadCliente.setFont(new Font("Dialog", 1, 12)); // NOI18N
        butCadCliente.setLabel("Clientes");
        getContentPane().add(butCadCliente);
        butCadCliente.setBounds(20, 420, 160, 50);
        butCadCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butCadClienteActionPerformed(evt);
            }
        });

        butCadFilme.setFont(new Font("Dialog", 1, 12)); // NOI18N
        butCadFilme.setLabel("Filmes");
        getContentPane().add(butCadFilme);
        butCadFilme.setBounds(190, 420, 160, 50);
        butCadFilme.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butCadFilmeActionPerformed(evt);
            }
        });

        butCadFuncionario.setFont(new Font("Dialog", 1, 12)); // NOI18N
        butCadFuncionario.setLabel("Funcionários");
        getContentPane().add(butCadFuncionario);
        butCadFuncionario.setBounds(360, 420, 160, 50);
        butCadFuncionario.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butCadFuncionarioActionPerformed(evt);
            }
        });

        butSessoes.setFont(new Font("Dialog", 1, 12)); // NOI18N
        butSessoes.setLabel("Sessões");
        getContentPane().add(butSessoes);
        butSessoes.setBounds(530, 420, 160, 50);
        butSessoes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butSessoesPerformed(evt);
            }
        });

        butIngressos.setFont(new Font("Dialog", 1, 12)); // NOI18N
        butIngressos.setLabel("Ingresso");
        getContentPane().add(butIngressos);
        butIngressos.setBounds(700, 420, 160, 50);
        butIngressos.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butIngressosActionPerformed(evt);
            }
        });

        pack();
    }
    private void jLabel6FocusGained(FocusEvent evt) {//GEN-FIRST:event_jLabel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6FocusGained

  private void butCadClienteActionPerformed (ActionEvent evt) {
        this.dispose();
        TelaCadCliente.desenha();
    }

  private void butCadFilmeActionPerformed (ActionEvent evt) {
        this.dispose();
        dlgMostraFilmes.desenha();
    }

      private void butSessoesPerformed (ActionEvent evt) {
        this.dispose();
        TelaSessoes.desenha();
    }

    private void butCadFuncionarioActionPerformed (ActionEvent evt) {
        this.dispose();
        dlgMostraFuncionarios.desenha();
    }

    private void butIngressosActionPerformed (ActionEvent evt) {
        this.dispose();
        TelaIngresso.desenha();
    }

    public static void desenha(){
        TelaDashBoard telaDashBoard = new TelaDashBoard();
        int width = 900;
        int height = 550;
        telaDashBoard.setSize(width, height);
        telaDashBoard.setLocationRelativeTo(null);
        telaDashBoard.setResizable(false);
        telaDashBoard.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDashBoard.desenha();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button butCadCliente;
    private Button butCadFilme;
    private Button butCadFuncionario;
    private Button butSessoes;
    private Button butIngressos;
    private JLabel jLabel1;
    private JLabel jLabel6;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
